name: Build and Commit

on:
  push:
    branches-ignore:
      - "main"

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push
        if: startsWith(github.ref, 'refs/heads/branch-')
        run: |
          git config --global user.name 'Spectrages'
          git config --global user.email 'specrages@gmail.com'
          git add -f build
          git commit -m "Add build files"
          git push
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages
          npx gh-pages -d build --repo "https://github.com/Spectrages/hosting_template_1.git"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
